.\" Manpage for the snakeSO script
.\" Contact: adrianszwaczyk@gmail.com
.TH snakeSO 6 "9 May 2023" "1.0" "Games"
.SH NAME
snakeSO - classic snake game implemented in bash. Have fun!
.SH SYNOPSIS
snakeSO (no special options, just start it and play!)
.SH DESCRIPTION
The snakeSO script is a classic snake game implemented in bash. Control the snake, eat as many apples (red squares) as possible, and increase your score and snake's length. The game ends if the snake collides with a wall or its own body.
.SH CONTROLS AND OPTIONS
.TP
\fBArrows\fP
- Move the snake in the corresponding direction.
.TP
\fBQ\fP
- Quit the game.
.TP
\fBH\fP
- Open the help window.
.TP
\fBI\fP
- Open the information window.
.SH BUGS
After exiting the game, the cursor in the console is not visible.
.SH AUTHOR
Written by Adrian Szwaczyk.
.SH REPORTING BUGS
Please report any bugs or issues to adrianszwaczyk@gmail.com.
.SH COPYRIGHT
This script is licensed under the GPL (GNU General Public License). For more details, refer to /usr/share/common-licenses/GPL or contact the Free Software Foundation for a copy of the license.